<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageVersion Include="WolverineFx" Version="6.29.1" />
    <PackageVersion Include="WolverineFx.Http" Version="6.29.1" />
    <PackageVersion Include="WolverineFx.Postgresql" Version="6.29.1" />
    <PackageVersion Include="WolverineFx.RuntimeCompilation" Version="6.29.1" />
  </ItemGroup>
</Project>