// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rezilio.Modules.Organization.Infrastructure;

#nullable disable

namespace Organization.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    partial class OrganizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rezilio.Modules.Organization.Domain.TenantSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tenant_settings", (string)null);
                });

            modelBuilder.Entity("Rezilio.Modules.Organization.Domain.TenantSettings", b =>
                {
                    b.OwnsMany("Rezilio.SharedKernel.DDD.VOs.LanguageCode", "SupportedLanguages", b1 =>
                        {
                            b1.Property<Guid>("TenantSettingsId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("TenantSettingsId", "__synthesizedOrdinal");

                            b1.ToTable("tenant_settings");

                            b1
                                .ToJson("supported_languages")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TenantSettingsId");
                        });

                    b.Navigation("SupportedLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
