// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rezilio.Modules.Licensing.Infrastructure;

#nullable disable

namespace Licensing.Infrastructure.Migrations
{
    [DbContext(typeof(LicensingDbContext))]
    partial class LicensingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rezilio.Modules.Licensing.Domain.TenantLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PlanExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("tenant_licenses", (string)null);
                });

            modelBuilder.Entity("Rezilio.Modules.Licensing.Domain.TenantLicense", b =>
                {
                    b.OwnsMany("Rezilio.Modules.Licensing.Domain.ModuleAccess", "ModuleAccesses", b1 =>
                        {
                            b1.Property<Guid>("TenantLicenseId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("IsActive");

                            b1.Property<string>("Module")
                                .IsRequired();

                            b1.Property<DateTimeOffset?>("TrialEndsAt");

                            b1.HasKey("TenantLicenseId", "__synthesizedOrdinal");

                            b1.ToTable("tenant_licenses");

                            b1
                                .ToJson("module_accesses")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TenantLicenseId");
                        });

                    b.Navigation("ModuleAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
